lensLook.Pl/Controllers/BasketController.cs
using lensLook.Dal;
using lensLook.Dal.models;
using lensLook.Dal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace lensLook.Pl.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketRepo _basketRepo;
        private readonly UserManager<user> userManager;
        private readonly IProductRepo productRepo;

        public BasketController(IBasketRepo BasketRepo, UserManager<user> userManager, IProductRepo productRepo)
        {
            _basketRepo = BasketRepo;
            this.userManager = userManager;
            this.productRepo = productRepo;
        }


        [Authorize]
        public async Task<IActionResult> AddToCart(int Product)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

            var OldBasket = _basketRepo.GetCustomerBasket(userId);

            var x = OldBasket.BasketItems.Where(x => x.Productid == Product).FirstOrDefault();
            if (x != null)
            {
                x.Quantity++;
            }
            else
            {
                var product = productRepo.GetProductById(Product);
                OldBasket.BasketItems.Add(new BasketItems
                {
                    Productid = Product,
                    Quantity = 1,
                    Photo = product.PictureUrl,
                    price = product.Price,
                    Name = product.Name,
                });

            }

            var StateUpdateOrDelete = _basketRepo.UpdateBasket(OldBasket);

            return RedirectToAction("store", "Home");


        }


        [Authorize]
        public IActionResult Cart()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

            var OldBasket = _basketRepo.GetCustomerBasketWithProduct(userId);
            return View(OldBasket);
        }

        [Authorize]
        public IActionResult IncrementProductFromBasket(int Id  /* ProductId*/  )
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

            var OldBasket = _basketRepo.GetCustomerBasket(userId);

            var x = OldBasket.BasketItems.Where(x => x.Productid == Id).FirstOrDefault();
            if (x != null)
            {
                x.Quantity++;
            }


            var StateUpdateOrDelete = _basketRepo.UpdateBasket(OldBasket);

            return RedirectToAction("Cart", "Basket");


        }       

        public IActionResult LessProductFromBasket(int Id)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

            var OldBasket = _basketRepo.GetCustomerBasket(userId);

            var x = OldBasket.BasketItems.Where(x => x.Productid == Id).FirstOrDefault();
            if (x != null)
            {
                if(x.Quantity>2)
                x.Quantity--;
                else
                {
                    OldBasket.BasketItems.Remove(x);
                }
            }


            var StateUpdateOrDelete = _basketRepo.UpdateBasket(OldBasket);

            return RedirectToAction("Cart", "Basket");
        }

        public IActionResult RemoveProductFromBasket(int Id)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

            var OldBasket = _basketRepo.GetCustomerBasket(userId);

            var x = OldBasket.BasketItems.Where(x => x.Productid == Id).FirstOrDefault();

            OldBasket.BasketItems.Remove(x);

            var StateUpdateOrDelete = _basketRepo.UpdateBasket(OldBasket);

            return RedirectToAction("Cart", "Basket");
        }

















    }
}

lensLook.Pl/Controllers/BookingController.cs
using AutoMapper;
using lensLook.Bll;
using lensLook.Bll.Services;
using lensLook.Dal.Models;
using lensLook.Pl.Models.BookingViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace lensLook.Pl.Controllers
{
    public class BookingController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IServicesRepo _servicesRepo;
        private readonly IRequestServices _requestService;

        public BookingController(IMapper mapper, IServicesRepo servicesRepo, IRequestServices requestService)
        {
            _mapper = mapper;
            _servicesRepo = servicesRepo;
            _requestService = requestService;
        }

        [HttpGet]
        public IActionResult Repair()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Repair(BookingCreateVm model)
        {
            return HandleBooking(model, "repairs");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Online()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Online(BookingCreateVm model)
        {
            return HandleBooking(model, "Online");
        }

        [HttpGet]
        public IActionResult Offline()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Offline(BookingCreateVm model)
        {
            return HandleBooking(model, "HomeVisit");
        }

        public IActionResult AllBookingForUser()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

            var allRequests = _requestService.GetServicesByUser(userId);
            return View(allRequests);
        }

        [Authorize(Roles = "Doctor")]
        public IActionResult Appointment()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (userId == null)
            {
                return Unauthorized();
            }

            var allRequests = _requestService.GetAllForDoctor(userId);
            return View(allRequests);
        }

        [Authorize(Roles = "Doctor")]
        public IActionResult AcceptRequest(int id)
        {
            return UpdateRequestStatus(id, BookingStatus.Accepted);
        }

        [Authorize(Roles = "Doctor")]
        public IActionResult RejectRequest(int id)
        {
            return UpdateRequestStatus(id, BookingStatus.Rejected);
        }




        private IActionResult HandleBooking(BookingCreateVm model, string serviceName)
        {
            if (ModelState.IsValid)
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                if (userId == null)
                {
                    return Unauthorized();
                }

                var booking = _mapper.Map<Booking>(model);
                booking.UserId = userId;
                var serviceType = _servicesRepo.GetByName(serviceName);
                booking.ServiceId = serviceType.Id;

                var result = _requestService.Create(booking);
                if (!result)
                {
                    return View(model);
                }

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        private IActionResult UpdateRequestStatus(int id, BookingStatus status)
        {
            var request = _requestService.GetById(id);
            if (request == null)
            {
                return NotFound();
            }

            request.Status = status;
            request.DoctorStatus = status;
            request.DoctorResponseTime = DateTime.Now;
            request.AdminStatus = status;

            _requestService.Update(request);
            return RedirectToAction(nameof(Appointment));
        }
    }
}

lensLook.Pl/Controllers/OrderController.cs
using lensLook.Bll.Services;
using lensLook.Dal;
using lensLook.Dal.Models;
using lensLook.Pl.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace lensLook.Pl.Controllers
{
	public class OrderController : Controller
	{
		private readonly IBasketRepo basketRepo;
		private readonly IProductRepo productRepo;
        private readonly IOrderService _orderServices;

        public OrderController(IBasketRepo _BasketRepo,IProductRepo productRepo , IOrderService orderServices)
        {
			basketRepo = _BasketRepo;
			this.productRepo = productRepo;
            _orderServices = orderServices;
        }


		[HttpGet]
		public IActionResult CreateOrder(int BasketCustomer)
		{
            var Basket = basketRepo.GetCustomerBasketWithProductById(BasketCustomer);
            if(Basket==null)
            {
                return RedirectToAction("Index", "Home");
            }
            var UserEmail = User.FindFirstValue(claimType: ClaimTypes.Email);

            var orderItems = new List<OrderItem>();

            foreach (var item in Basket.BasketItems)
            {
                var Product = productRepo.GetProductById(item.Productid);

                orderItems.Add(new OrderItem(new ProductItemOrder(item.Id, item.Name, item.Product.PictureUrl), item.price, item.Quantity));

            }

            var Orders = new Order(UserEmail, "", Basket.TotalPrice, orderItems);
            return View(Orders);

        }


        [HttpPost]
        public async Task<IActionResult> CreateOrder(Order model)
        {

            var UserId= User.FindFirstValue(claimType:ClaimTypes.NameIdentifier);
            var Basket=basketRepo.GetCustomerBasket(UserId);
            var BasketWithOrder = basketRepo.GetCustomerBasketWithProductById(Basket.Id);

            var orderItems = new List<OrderItem>();

            foreach (var item in Basket.BasketItems)
            {
                var Product = productRepo.GetProductById(item.Productid);

                orderItems.Add(new OrderItem(new ProductItemOrder(item.Id, item.Name, item.Product.PictureUrl), item.price, item.Quantity));

            }

            model.UserIdCreateOrder = UserId;
            model.Items = orderItems;

            await _orderServices.CreateOrderAsync(model);
            return RedirectToAction("Index", "Home");
        }



        [HttpGet]
        public IActionResult AllOrderForUser()
        {
            var UserId = User.FindFirstValue(claimType: ClaimTypes.NameIdentifier);
            var orders=_orderServices.GetOrdersForUser(UserId);  


            return View(orders);
        }

        [HttpGet]
        public IActionResult OrderDetails(int orderId)
        {

            var orders = _orderServices.GetOrderById(orderId);



                return View(orders);
        }


        [HttpGet]
        public IActionResult RemoveOrder(int orderId)
        {
            _orderServices.RemoveOrder(orderId);
            return RedirectToAction("Cart","Basket");
        }

    }
}

lensLook.Pl/Views/Basket/Cart.cshtml
@model BasketCustomer
@inject IOrderService _OrderServices;
@inject IRequestServices _Request;

@{
    var UserId = User.FindFirstValue(claimType: ClaimTypes.NameIdentifier);

    Layout = "_LayoutWithAuth";
}

@section Linkedcss{
    <style>
/*         :root {
            --myblue: #033373;
            --mylight: #17b8da;
            --mywhite: white;
            --mylightblue: #03347310;
            --mydoctorblue: #03347377;
            --transition: 0.3s ease-in-out;
            --animation: left_right 2s ease-in-out;
            --bottom_up: bottomUp 2s ease-in-out forwards;
            --left_right: left_right 2s ease-in-out forwards;
            --my_shadow: 0px 0px 15px -5px var(--myblue);
        } */
        .container.py-5 {
            max-width: none !important;
        }
    </style>

}







<section class="h-100 gradient-custom">




    <div class="container py-5">
        <div class="row d-flex justify-content-center my-4">

            <div class="col-md-8 ">

                <div class="d-flex justify-content-between">
                    @{
                        if (_OrderServices.GetOrdersForUser(UserId).Count() > 0)
                        {
                            <a class="btn main-btn mb-2"  asp-action="AllOrderForUser" asp-controller="Order">orders </a>
                        }


                        if (_Request.GetServicesByUser(UserId).Count() > 0)
                        {
                            <a class="btn main-btn mb-2" asp-action="AllBookingForUser" asp-controller="Booking">Booking </a>
                        }


                    }

                    </di>
                </div>

                @if (@Model.BasketItems.Count() > 0)
                {
                    <div class="card mb-4">
                        <div class="card-header py-3" style="color:#033373">
                            <h5 class="mb-0">Cart - @Model.BasketItems.Count() items</h5>
                        </div>


                        <div class="card-body">
                            <!-- Single item -->
                            @foreach (var item in Model.BasketItems)
                            {


                                <div class="row">
                                    <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                                        <!-- Image -->
                                        <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                                            <img src="@item.Photo"
                                                 class="w-100" alt="@item.Name" />
                                            <a href="#!">
                                                <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                                            </a>
                                        </div>
                                        <!-- Image -->
                                    </div>

                                    <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                                        <!-- Data -->
                                        <p style="color: #033373"><strong>@item.Name</strong></p>
                                        <p><span style="color: #033373">Color:</span> blue</p>
                                        <p><span style="color: #033373">Size:</span> M</p>
                                        <a asp-action="RemoveProductFromBasket" asp-controller="Basket" asp-route-Id="@item.Productid" type="button" data-mdb-button-init data-mdb-ripple-init style="background-color: #033373; color:#fff" class="btn   btn-sm me-1 mb-2" data-mdb-tooltip-init
                                           title="Remove item">
                                            <i class="fas fa-trash "></i>
                                        </a>

                                        <!-- Data -->
                                    </div>

                                    <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                                        <!-- Quantity -->
                                        <div class="d-flex mb-4" style="max-width: 300px">
                                            <a asp-action="LessProductFromBasket" asp-controller="Basket" asp-route-Id="@item.Productid" data-mdb-button-init data-mdb-ripple-init class="btn px-3 me-2" style="background-color:#17b8da; color:#fff"
                                               onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                                <i class="fas fa-minus"></i>
                                            </a>

                                            <div data-mdb-input-init class="form-outline">
                                                <input id="form1" min="0" name="quantity" value="@item.Quantity" type="number" class="text-center form-control " disabled />
                                                @* <label class="form-label" for="form1">Quantity</label> *@
                                            </div>

                                            <a asp-action="IncrementProductFromBasket" asp-controller="Basket" asp-route-Id="@item.Productid" data-mdb-button-init data-mdb-ripple-init class="btn px-3 ms-2" style="background-color: #033373; color:#fff"
                                               onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                        </div>
                                        <!-- Quantity -->
                                        <!-- Price -->
                                        <p class="text-start text-md-center">
                                            <strong>@(@item.price * @item.Quantity)</strong>
                                        </p>
                                        <!-- Price -->
                                    </div>
                                </div>
                                <!-- Single item -->

                                <hr class="my-4" />

                            }



                            <!-- Single item -->
                            <!-- Single item -->
                        </div>

                    </div>
                }



            </div>
            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-header py-3">
                        <h5 class="mb-0" style="color: #033373">Summary</h5>
                    </div>
                    <div class="card-body" >
                        <ul class="list-group list-group-flush" >
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0" style="color: #033373">
                                Products
                                <span >@Model.TotalPrice</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0" style="color: #033373">
                                Shipping
                                <span >Gratis</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                                <div>
                                    <strong style="color:#033373">Total amount</strong>
                                    <strong style="color:#17b8da">
                                        <p class="mb-0">(including VAT)</p>
                                    </strong>
                                </div>
                                <span style="color: #033373"><strong>@Model.TotalPrice</strong></span>
                            </li>
                        </ul>

                        @if (Model.BasketItems.Count > 0)
                        {
                            <a class="main-btn" asp-controller="Order" asp-action="CreateOrder" asp-route-BasketCustomer="@Model.Id" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-lg btn-block">
                                Go to checkout
                            </a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>